# rtfcommands
game.message.starting=<rainbow>The game will start in {0}s</rainbow>
game.message.started=Game starts, good luck!
game.message.client.leave.starting=There are not enough players to start the game.
join.already.in.team=You are already in a team.
player.join.team={0} joined {1} team.
player.pickup.flag={0} picked the {1} flag!
player.pickup.flag.info=You are in possession of the enemy flag. Your goal is to return home to place it below your flag.
player.place.flag={0} placed the {1} flag!
player.pickup.own.flag=You cant pick your own team flag!
scoreboard.waiting=Waiting for players {0}/{1}
scoreboard.starting=Game starts in {0}
scoreboard.started=Game time: {0}
scoreboard.ending=WINNER! {0}
scoreboard.spectate.mode=SPECTATE MODE
scoreboard.spectate.join.usage=Use {0}
scoreboard.team=Your team: {0}
scoreboard.kills=Kills: {0}
scoreboard.deaths=Deaths: {0}
scoreboard.attempts=Attempts: {0}
scoreboard.flag.stolen={0}: Stolen
scoreboard.flag.placed={0}: In place
game.end.win=The {0} team has won the game!
game.end.other=The game must have ended suddenly.
menu.kits.title=Choose a kit

# rtfcommands
game.already.exists=A rtf instance already exists!

# kits
kit.rusher.name=Rusher
kit.rusher.description=The most basic kit!
kit.tank.name=Tank
kit.tank.description=The final boss is coming!
kit.archer.name=Archer
kit.archer.description=Do not spam too much arrows!
kit.engineer.name=Engineer
kit.engineer.description=Be smart, and use your utilities!
kit.switcher.name=Switcher
kit.switcher.description=Outsmart your opponents by switching places!
kit.kamikaze.name=Kamikaze
kit.kamikaze.description=Go out with a bang and take your enemies with you!
kit.speedster.name=Speedster
kit.speedster.description=Zoom past your enemies with incredible speed!
kit.nokit.name=NoKit
kit.nokit.description=Enter the battle with nothing but your wits!

# Win
game.end.time=The elapsed time is {0}.
game.end.top=Top 3 best players:
game.end.top.1=1st - {0}
game.end.top.2=2nd - {0}
game.end.top.3=3rd - {0}

game.player.spectate=You are currently a spectator of the game. To join the game, use {0}.
game.player.spectate.hover=Click to join!
player.death.killed={0} has been killed by {1}
player.death.void={0} fell into the void
player.death.fall={0} broke his legs
player.death.with.flag={0} with the {1} flag!
respawn.time.remaining=Respawn in {0}...
respawn.end.go=GO !
game.not.exists=This game not exists.
